name: CI - Java

on: [pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Verify with Maven
        working-directory: ./server
        run: mvn --batch-mode --update-snapshots verify
